### ISSUE TITLE
可使用light gallery作者发布的cdn

### ISSUE THREAD

**Issue by jrh8182** [lzane/hexo-light-gallery#11]
链接如下：
https://www.jsdelivr.com/?query=author%3A%20sachinchoolur

```
lightgallery:
  js: 'https://cdn.jsdelivr.net/npm/lightgallery.js@1.4.0/dist/js/lightgallery.min.js'
  css: 'https://cdn.jsdelivr.net/npm/lightgallery.js@1.4.0/dist/css/lightgallery.min.css'
  plugins:
    lg-thumbnail.js: 'https://cdn.jsdelivr.net/npm/lg-thumbnail.js@1.2.0/dist/lg-thumbnail.min.js'
    lg-fullscreen.js: 'https://cdn.jsdelivr.net/npm/lg-fullscreen.js@1.2.0/dist/lg-fullscreen.min.js'
    lg-zoom.js: 'https://cdn.jsdelivr.net/npm/lg-zoom.js@1.3.0/dist/lg-zoom.min.js'
    lg-autoplay.js: 'https://cdn.jsdelivr.net/npm/lg-autoplay.js@1.2.0/dist/lg-autoplay.min.js'
    lg-video.js: 'https://cdn.jsdelivr.net/npm/lg-video.js@1.3.0/dist/lg-video.min.js'
    lg-hash.js: 'https://cdn.jsdelivr.net/npm/lg-hash.js@1.0.0/dist/lg-hash.min.js'
    lg-pager.js: 'https://cdn.jsdelivr.net/npm/lg-pager.js@1.0.0/dist/lg-pager.min.js'
```
